### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by pgrycz** [drelyn86/atom-terminus#4]
I've tried it to open git-bash.exe (set with proper installation path) from working project directory and there's no response

**Comment by duhdugg** [comment]
It does work. Is the issue actually that it doesn't work with git-bash.exe? Please be specific in your issue reporting.

**Comment by pgrycz** [comment]
yes, with git-bash.exe doesn't work

2017-08-29 21:32 GMT+02:00 Doug Elkin <notifications@github.com>:

**Comment by duhdugg** [comment]
Are you sure you're using it correctly? git-bash is a shell which is launched by a terminal. The terminal that is selected during the installation process for "Git for Windows" by default is mintty and can be found at C:\Program Files\Git\usr\bin\mintty.exe

See https://mintty.github.io/ for usage.

**Comment by pgrycz** [comment]
oh I see, will check that out, thanks, if something I'll give a feedback

2017-08-30 16:54 GMT+02:00 Doug Elkin <notifications@github.com>:
