### ISSUE TITLE
Cannot run sudo

### ISSUE THREAD

**Issue by iJustErikk** [drelyn86/atom-terminus#8]
Hey I tried to run sudo and it spat this out:
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system w
ithout root privileges?
Attemping to su into user meets me with an auth fail even if it is the correct password.

**Comment by duhdugg** [comment]
This is a problem with the permissions on your system and is not relevant to this package.
